### ISSUE TITLE
Does not work when installed with yarn

### ISSUE THREAD

**Issue by calebeby** [jstransformers/jstransformer-absurd#6]
For some reason, the tests fail with yarn, but not npm. I don't have time to look into it right now, but here is the error:

```
 • absurd
   ✓ transform has an output format (1ms)
   ✓ transform has input formats (0ms)
   • advanced
     ✗ absurd.render() (213ms)

       TypeError: Cannot read property 'apply' of null
           at /home/caleb/Programming/jstransformers/jstransformer-absurd/node_modules/absurd/lib/api/compile.js:35:14
           at Object.processor (/home/caleb/Programming/jstransformers/jstransformer-absurd/node_modules/absurd/lib/processors/css/CSS.js:186:17)
           at Object.<anonymous> (/home/caleb/Programming/jstransformers/jstransformer-absurd/node_modules/absurd/lib/api/compile.js:23:11)
           at Object.compile (/home/caleb/Programming/jstransformers/jstransformer-absurd/node_modules/absurd/lib/API.js:117:16)
           at Object.exports.render (/home/caleb/Programming/jstransformers/jstransformer-absurd/index.js:69:54)
           at TestCase.fn (/home/caleb/Programming/jstransformers/jstransformer-absurd/node_modules/test-jstransformer/index.js:133:32)
           at /home/caleb/Programming/jstransformers/jstransformer-absurd/node_modules/testit/lib/suite.js:74:29
           at tryCallOne (/home/caleb/Programming/jstransformers/jstransformer-absurd/node_modules/promise/lib/core.js:37:12)
           at /home/caleb/Programming/jstransformers/jstransformer-absurd/node_modules/promise/lib/core.js:123:15
           at flush (/home/caleb/Programming/jstransformers/jstransformer-absurd/node_modules/asap/raw.js:50:29)

Total duration 242ms
tests failed
npm ERR! Test failed.  See above for more details.
```

**Comment by RobLoach** [comment]
Interesting.
